[package]
name = "builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary = { path = "../binary", artifact = "cdylib", target = "wasm32-unknown-unknown" }
